In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
import os

In [3]:
#pandas 绘图可以基于df对象直接绘图，他的底层依赖matplotlib

#1.加载数据,并设置第一列为索引列
df=pd.read_csv('../data/winemag-data_first150k.csv',index_col=0)
df.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [5]:
#2.查看数据集信息
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 150930 entries, 0 to 150929
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   country      150925 non-null  str
 1   description  150930 non-null  str
 2   designation  105195 non-null  str
 3   points       150930 non-null  int64
 4   price        137235 non-null  float64
 5   province     150925 non-null  str
 6   region_1     125870 non-null  str
 7   region_2     60953 non-null   str
 8   variety      150930 non-null  str
 9   winery       150930 non-null  str
dtypes: float64(1), int64(1), str(8)
memory usage: 55.6 MB

              points          price
count  150930.000000  137235.000000
mean       87.888418      33.131482
std         3.222392      36.322536
min        80.000000       4.000000
25%        86.000000      16.000000
50%        88.000000      24.000000
75%        90.000000      40.000000
max       100.000000    2300.000000

In [ ]:
#https://www.bilibili.com/video/BV1ReshzoEgG/?spm_id_from=333.788.player.switch&vd_source=c17e5dfc5f61fa885254eb32803f9fbb&p=141